### PR TITLE
Feat/toast

### PR DESCRIPTION
**Pull request by ajay-mandaviya**
make a toaster component
Screenshot from 2022-02-08 22-19-04

### CODE REVIEW

**Review by rushikesh3299 — COMMENTED** [review]
Looks good to me. You can merge.

**Review by ArjunGTX — APPROVED** [review]
Everything looks perfect

**Comment by spraveenofficial** [comment]
I think, dismiss button in center will make much more attractive and minimal. 

Code looking good.

**Review by nerdyspook — APPROVED** [review]
The code looks good, you can merge it.

**Comment by ajay-mandaviya** [comment]
> I think, dismiss button in center will make much more attractive and minimal.
> 
> Code looking good.

Yes , but no need to make it center

**Comment by ajay-mandaviya** [comment]
> Looks good to me. You can merge.

Thanks for review

**Comment by ajay-mandaviya** [comment]
> Everything looks perfect

thanks for review

**Pull request merged**
